Setup NVD on linux
UKHO/vm-agent-aib pull request #18
Opened 2020-03-18 14:14 UTC by elduddz

2020-03-18 15:23 UTC, eganjs requested changes

2020-03-18 15:23 UTC, eganjs commented on customscriptextension.sh
> +mkdir /etc/smbcredentials
indent this line

2020-03-18 15:23 UTC, eganjs commented on customscriptextension.sh
> +fi
this could be shortened to
```bash
[ ! -d "/etc/smbcredentials" ] && mkdir /etc/smbcredentials
```
or
```bash
[ -d "/etc/smbcredentials" ] || mkdir /etc/smbcredentials
```
Using `install` instead of `mkdir` may also be more favourable, as you can set permissions and owners on the directory as you create it, e.g.
```bash
install --mode=600 -d /etc/smbcredentials
```
`install` is also idempotent so you wouldn't need the if statement

2020-03-18 15:23 UTC, eganjs commented on customscriptextension.sh
> +fi
This could be rewritten as a heredoc e.g.
```bash
cat <<EOF > /etc/smbcredentials/${storageaccountuser}.cred
username=${storageaccountuser}
password=${storageaccountpassword}
EOF
```
and then as above
```bash
[ ! -f "/etc/smbcredentials/${storageaccountuser}.cred" ] && cat <<EOF > /etc/smbcredentials/${storageaccountuser}.cred
username=${storageaccountuser}
password=${storageaccountpassword}
EOF
```
or
```bash
[ -f "/etc/smbcredentials/${storageaccountuser}.cred" ] || cat <<EOF > /etc/smbcredentials/${storageaccountuser}.cred
username=${storageaccountuser}
password=${storageaccountpassword}
EOF
```
Another alternative would be using a fifo to hold the file's contents temporarily, then perform the write to disk and set the permissions in one go with `install`:
```bash
fifo=$(mktemp)
mkfifo ${fifo}
install --mode=600 ${fifo} "/etc/smbcredentials/${storageaccountuser}.cred" &
cat <<EOF > ${fifo}
username=${storageaccountuser}
password=${storageaccountpassword}
EOF
rm ${fifo}
```

2020-03-18 15:23 UTC, eganjs commented on customscriptextension.sh
> +export PATH=$PATH:/mnt/${mountpoint}/dependency-check/bin
```suggestion
export PATH=${PATH}:/mnt/${mountpoint}/dependency-check/bin
```

2020-03-18 15:25 UTC, elduddz commented on customscriptextension.sh
> +mkdir /etc/smbcredentials
```suggestion
    mkdir /etc/smbcredentials
```

2020-03-18 15:26 UTC, elduddz commented on customscriptextension.sh
> +fi
this is code provided, didnt want to nudge it too much I thought removing the sudo was enough :)

2020-03-18 15:27 UTC, elduddz commented on customscriptextension.sh
> +fi
you know you can put these in as suggestions :)

2020-03-18 15:30 UTC, elduddz commented on customscriptextension.sh
> +fi
does the fifo delete the cred? The cred needs to persist.

2020-03-18 15:55 UTC, eganjs commented on customscriptextension.sh
> +fi
https://www.howtoforge.com/linux-mkfifo-command/ does a good job explaining `mkfifo`

2020-03-18 15:57 UTC, eganjs commented on customscriptextension.sh
> +fi
The cred file is created with `install` the fifo just provides the content

2020-03-18 16:02 UTC, eganjs commented on customscriptextension.sh
> +fi
If you think the if statement is more readable I think that is reason enough to leave it as is :)

2020-03-18 22:27 UTC, elduddz commented
I still cannot get it to export a value to the capability on the agent. not sure what you have to do...

2020-03-19 10:41 UTC, eganjs approved these changes

2020-03-19 10:55 UTC, merged